# Generated by Django 4.2.2 on 2023-07-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg'),
            preserve_default=False,
        ),
    ]
